---
- name: Update APT package list
  ansible.builtin.apt:
    update_cache: yes

- name: Transfer SSH private key to the slave
  ansible.builtin.copy:
    src: "/home/mohamed/.ssh/Key"
    dest: "/home/ubuntu/.ssh/Key"
    mode: "0400"
    owner: ubuntu
    group: ubuntu

- name: Transfer Terraform Outputs to the slave
  ansible.builtin.copy:
    src: "../Scripts/TF-Outputs.json"
    dest: "/home/ubuntu/TF-Outputs.json"
    mode: "0644"
    owner: ubuntu
    group: ubuntu

- name: Install Packages and Modules
  ansible.builtin.apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  loop:
    - {name: "unzip", state: "present"}
    - {name: "openjdk-21-jre", state: "present"}
    - {name: "ansible", state: "present"}
    - {name: "docker.io", state: "present"}


- name: Download AWS CLI
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip
    mode: '0644'
    register: aws_exists

- name: Unzip AWS CLI
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp
    remote_src: yes
    when: aws_exists.changed == true

- name: Install AWS CLI
  become: true
  ansible.builtin.command:
    cmd: /tmp/aws/install --bin-dir /usr/local/bin --install-dir /usr/local/aws-cli --update
    when: aws_exists.changed == true

- name: Start and enable Docker service
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes

- name: Add ubuntu user to Docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
    
- name: Create jenkins directory
  ansible.builtin.file:
    path: "/home/ubuntu/jenkins"
    state: directory
    mode: "0755"
    owner: ubuntu
    group: ubuntu