---
- name: Update APT package list
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes

- name: Disable Host Nginx
  ansible.builtin.service:
    name: nginx
    state: stopped
    enabled: 
    
- name: Stop and delete the old container
  ansible.builtin.shell: |
    docker stop landing_page && docker rm landing_page
  ignore_errors: true

- name: Remove old app image and pull the new one
  ansible.builtin.shell: |
    docker image rm {{ image_name }}:latest && docker pull {{ image_name }}:latest
  ignore_errors: true
    
- name: Run new container from updated image
  ansible.builtin.command: >
    docker run -d
    --name landing_page
    -p 80:80
    --restart always
    {{ image_name }}:latest