---
- name: Update APT package list
  ansible.builtin.apt:
    update_cache: yes

- name: Disable Host Nginx
  ansible.builtin.sysvinit:
    name: nginx
    state: stopped
    enabled: false

- name: Ensure Docker is installed
  command: docker --version
  register: docker_installed
  failed_when: docker_installed.rc != 0
  changed_when: false

- name: Remove old landing_page image if exists
  command: docker image rm {{ image_name }}:latest
  ignore_errors: yes

- name: Pull latest old landing_page image
  command: docker pull {{ image_name }}:latest

- name: Stop running container (if exists)
  command: docker stop landing_page
  ignore_errors: yes

- name: Remove existing container (if exists)
  command: docker rm landing_page
  ignore_errors: yes

- name: Run new container from updated image
  command: >
    docker run -d
    --name landing_page
    -p 80:80
    --restart always
    {{ image_name }}:latest